# checkov:skip=CKV_DOCKER_3: "Ensure that a user for the container has been created"
# GitHub actions require that the docker image use the root user
# https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user

# Ubuntu 24.04 LTS provides modern autotools: automake 1.16.5, autoconf 2.71, libtool 2.4.7
# This is used for bootstrap libraries (GMP, MPFR, MPC, ISL, Expat, libiconv)
# Legacy autoconf 2.69 is also installed for binutils/gcc/gdb/newlib compatibility
FROM ubuntu:24.04 AS bootstrap

##########################################
### Bootstrap: Install Build Tools    ###
###                                    ###
### Installs autotools and build       ###
### prerequisites, then builds         ###
### foundational libraries needed by   ###
### GCC (GMP, MPFR, MPC, ISL, EXPAT,   ###
### zlib). See docs/automake-          ###
### modernization-stage-mapping.md     ###
### for detailed autotools usage.      ###
##########################################
RUN ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime && \
    sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get --yes upgrade && \
    apt-get install --yes --no-install-recommends \
        autoconf \
        autoconf2.69 \
        automake \
        autogen \
        libtool \
        bison \
        build-essential \
        flex \
        git \
        python3 \
        texinfo \
        texlive && \
    rm -rf /var/lib/apt/lists/*

# Autotools packages installed:
# - autoconf:        Modern autoconf 2.71 (Ubuntu 24.04 default) for bootstrap libraries (gmp, mpfr, mpc, isl, expat, libiconv)
# - autoconf2.69:    Legacy version required for binutils/gcc/gdb/newlib (exact version 2.69 needed for reproducible builds)
# - automake:        For processing Makefile.am → Makefile.in (all libraries using automake)
# - autogen:         For processing Makefile.def → Makefile.in (binutils, gcc, gdb, newlib)
# - libtool:         For building shared/static libraries

# Create build area
RUN mkdir -p /root/build/gnu-tools-for-stm32/

# Copy build scripts first (these change more frequently than source code)
# Copying these separately allows Docker to cache the large source copy below
WORKDIR /root/build/gnu-tools-for-stm32
COPY build-common.sh build-toolchain-config.sh build-prerequisites.sh ./

# Copy only the source directories needed for bootstrap stage
# This separates frequently-changed scripts from rarely-changed source code
COPY src/gmp ./src/gmp
COPY src/mpfr ./src/mpfr
COPY src/mpc ./src/mpc
COPY src/isl ./src/isl
COPY src/expat ./src/expat
COPY src/libiconv ./src/libiconv
COPY src/zlib-1.2.12 ./src/zlib-1.2.12
COPY src/liblongpath-win32 ./src/liblongpath-win32

# Build bootstrap prerequisites (foundational libraries needed by GCC)
# Script: build-prerequisites.sh
# 
# Libraries built with MODERN AUTOTOOLS (autoconf 2.71, automake 1.16.5, libtool 2.4.6):
# 1. zlib (1.2.12):    Compression library (custom configure script, not autoconf-generated)
#                      Autogenerated files tracked: 2 (configure, Makefile.in)
# 2. GMP (6.2.1):      Multiple precision arithmetic library (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 0 (regenerated via regenerate_autotools())
# 3. MPFR (3.1.6):     Multiple precision floating-point library (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 0 (regenerated via regenerate_autotools())
# 4. MPC (1.0.3):      Complex number arithmetic library (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 0 (regenerated via regenerate_autotools())
# 5. ISL (0.18):       Integer set library for polyhedral compilation (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 1 (isl_config.h.in)
# 6. Expat (2.2.6):    XML parser library for GDB (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 1 (expat_config.h.in)
# 7. libiconv (1.16):  Character encoding conversion library (uses autoconf 2.71)
#                      Autogenerated files tracked: 8 (Makefile.in files)
#
# The regenerate_autotools() function (build-common.sh) regenerates configure, Makefile.in,
# and other autotools files for GMP, MPFR, MPC, ISL, Expat, and libiconv before building using
# modern autoconf 2.71 (Ubuntu 24.04 default). Only binutils/gcc/gdb/newlib use legacy autoconf 2.69.
RUN ./build-prerequisites.sh --skip_steps=mingw && \
    # Clean up temporary build directories to free up space.
    # Note: Installed libraries in build-native/host-libs/usr/lib/ are preserved for the toolchain build.
    rm -rf build-native/zlib build-native/gmp build-native/mpfr \
           build-native/mpc build-native/isl build-native/expat

##########################################
### Stage 1: Binutils + GCC First     ###
###                                    ###
### Builds GNU Binutils (assembler,   ###
### linker, etc.) and GCC first pass  ###
### (C compiler only, no headers).    ###
### Required to build the C library.  ###
###                                    ###
### Script: build-binutils-gcc-first.sh
###                                    ###
### Components built:                 ###
### 1. GNU Binutils                   ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      8 (subdirectory Makefile.in) ###
###    - Tools: as, ld, ar, nm, etc.  ###
###                                    ###
### 2. GCC First Pass                 ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      15 (hand-crafted Makefile.in)###
###    - Reduced from 22 (2025-11-11) ###
###    - C compiler only, no libs     ###
##########################################
FROM bootstrap AS binutils-gcc-first

WORKDIR /root/build/gnu-tools-for-stm32

# Copy build script and source code needed for this stage
COPY build-binutils-gcc-first.sh ./
COPY src/binutils ./src/binutils
COPY src/gcc ./src/gcc

RUN chmod +x build-binutils-gcc-first.sh && \
    ./build-binutils-gcc-first.sh

##########################################
### Stage 2: Newlib                   ###
###                                    ###
### Builds newlib, the C standard     ###
### library for embedded systems.     ###
### Provides libc, libm, and runtime  ###
### libraries. Uses the GCC first     ###
### pass compiler from Stage 1.       ###
###                                    ###
### Script: build-newlib.sh           ###
###                                    ###
### Component built:                  ###
### 1. Newlib                         ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      15 (hand-crafted Makefile.in ###
###      in libgloss subdirectories)  ###
###    - Reduced from 17 (2025-11-12) ###
###    - Libraries: libc.a, libm.a,   ###
###      libg.a, crt0.o startup files ###
###    - Built with -Os for size      ###
###      optimization                 ###
###    - Modernized: 2025-11-12       ###
###      (see docs/modernization-     ###
###      newlib.md)                   ###
##########################################
FROM binutils-gcc-first AS newlib

WORKDIR /root/build/gnu-tools-for-stm32

# Copy build script and source code needed for this stage
COPY build-newlib.sh ./
COPY src/newlib ./src/newlib

RUN chmod +x build-newlib.sh && \
    ./build-newlib.sh

##########################################
### Stage 3: GCC Final + GDB          ###
###                                    ###
### Builds GCC final pass with C++    ###
### support (creates libstdc++) and   ###
### GDB debugger. This is the         ###
### complete compiler toolchain.      ###
###                                    ###
### Script: build-gcc-final-gdb.sh    ###
###                                    ###
### Components built:                 ###
### 1. GCC Final Pass                 ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      15 (hand-crafted Makefile.in)###
###    - Reduced from 22 (2025-11-11) ###
###    - C and C++ compiler           ###
###    - Libraries: libstdc++.a,      ###
###      libsupc++.a                  ###
###                                    ###
### 2. GDB (GNU Debugger)             ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      95 (most of any component,   ###
###      includes many subdirectories ###
###      like bfd, binutils, gas,     ###
###      gdb, opcodes, readline, sim) ###
###    - Debugger for ARM targets     ###
##########################################
FROM newlib AS gcc-final-gdb

WORKDIR /root/build/gnu-tools-for-stm32

# Copy build script and source code needed for this stage
# Note: gcc source was already copied in binutils-gcc-first stage,
# but we need to copy it again since we're in a new stage
COPY build-gcc-final-gdb.sh ./
COPY src/gcc ./src/gcc
COPY src/gdb ./src/gdb

RUN chmod +x build-gcc-final-gdb.sh && \
    ./build-gcc-final-gdb.sh

##########################################
### Stage 4: Runtime Libraries        ###
###                                    ###
### Finalizes runtime library         ###
### installation (libstdc++, newlib)  ###
### and removes build artifacts.      ###
###                                    ###
### Script: build-runtime-libs-       ###
###         finalize.sh                ###
###                                    ###
### Operations:                        ###
### - Verifies runtime libraries      ###
### - Links toolchain binaries to     ###
###   /usr/local/bin/                 ###
### - Cleans up build artifacts       ###
###                                    ###
### No new libraries built, no        ###
### autotools usage in this stage.    ###
##########################################
FROM gcc-final-gdb AS runtime-libs

WORKDIR /root/build/gnu-tools-for-stm32

# Copy build script needed for this stage
COPY build-runtime-libs-finalize.sh ./

RUN chmod +x build-runtime-libs-finalize.sh && \
    ./build-runtime-libs-finalize.sh

##########################################
### Main: Final Stage                 ###
###                                    ###
### Complete toolchain ready for use  ###
### with all runtime libraries.       ###
###                                    ###
### Inherits all built tools from     ###
### previous stages. No additional    ###
### build operations or autotools     ###
### usage in this stage.              ###
###                                    ###
### Adds CMake and sets up the        ###
### entrypoint for building projects. ###
##########################################
FROM runtime-libs AS main

# Install CMake for building test projects
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        cmake && \
    rm -rf /var/lib/apt/lists/*

# Add toolchain binaries to PATH
ENV PATH="/root/build/gnu-tools-for-stm32/install-native/bin:${PATH}"

# Copy the generic entrypoint script
COPY build-cmake-project.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/build-cmake-project.sh

# Set working directory
WORKDIR /root/build/gnu-tools-for-stm32

# Set entrypoint to the generic build script
ENTRYPOINT ["/usr/local/bin/build-cmake-project.sh"]
