# checkov:skip=CKV_DOCKER_3: "Ensure that a user for the container has been created"
# GitHub actions require that the docker image use the root user
# https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user

# Ubuntu 24.04 LTS provides modern autotools: automake 1.16.5, autoconf 2.71, libtool 2.4.7
# This is used for bootstrap libraries (GMP, MPFR, MPC, ISL, Expat, libiconv)
# Legacy autoconf 2.69 is also installed for binutils/gcc/gdb/newlib compatibility
FROM ubuntu:24.04 AS bootstrap

##########################################
### Bootstrap: Install Build Tools    ###
###                                    ###
### Installs autotools and build       ###
### prerequisites, then builds         ###
### foundational libraries needed by   ###
### GCC (GMP, MPFR, MPC, ISL, EXPAT,   ###
### zlib). See docs/automake-          ###
### modernization-stage-mapping.md     ###
### for detailed autotools usage.      ###
##########################################
RUN ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime && \
    sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get --yes upgrade && \
    apt-get install --yes --no-install-recommends \
        autoconf \
        autoconf2.69 \
        automake \
        autogen \
        libtool \
        bison \
        build-essential \
        flex \
        git \
        python3 \
        texinfo \
        texlive && \
    rm -rf /var/lib/apt/lists/*

# Autotools packages installed:
# - autoconf:        Modern autoconf 2.71 (Ubuntu 24.04 default) for bootstrap libraries (gmp, mpfr, mpc, isl, expat, libiconv)
# - autoconf2.69:    Legacy version required for binutils/gcc/gdb/newlib (exact version 2.69 needed for reproducible builds)
# - automake:        For processing Makefile.am → Makefile.in (all libraries using automake)
# - autogen:         For processing Makefile.def → Makefile.in (binutils, gcc, gdb, newlib)
# - libtool:         For building shared/static libraries

# Create build area and copy only files needed for bootstrap stage
# This improves Docker layer caching - changes to main toolchain sources (gcc, gdb, binutils, newlib)
# won't invalidate the bootstrap layer cache

# Copy build scripts required for bootstrap
COPY build-common.sh build-toolchain-config.sh build-prerequisites.sh /root/build/gnu-tools-for-stm32/

# Copy GCC version file needed by build-common.sh (even though we don't build gcc yet)
# COPY automatically creates the necessary directory structure
COPY src/gcc/gcc/BASE-VER /root/build/gnu-tools-for-stm32/src/gcc/gcc/BASE-VER

# Copy only bootstrap library sources (prerequisites for GCC)
# Excluding main toolchain sources (gcc, gdb, binutils, newlib) - they're not needed until later stages
# Note: libiconv is copied for build script compatibility but only built for MinGW (Windows) targets
COPY src/gmp /root/build/gnu-tools-for-stm32/src/gmp
COPY src/mpfr /root/build/gnu-tools-for-stm32/src/mpfr
COPY src/mpc /root/build/gnu-tools-for-stm32/src/mpc
COPY src/isl /root/build/gnu-tools-for-stm32/src/isl
COPY src/expat /root/build/gnu-tools-for-stm32/src/expat
COPY src/zlib-1.2.12 /root/build/gnu-tools-for-stm32/src/zlib-1.2.12
COPY src/libiconv /root/build/gnu-tools-for-stm32/src/libiconv

# Build bootstrap prerequisites (foundational libraries needed by GCC)
# Script: build-prerequisites.sh --skip_steps=mingw
# 
# Libraries built in Docker native build with MODERN AUTOTOOLS (autoconf 2.71, automake 1.16.5, libtool 2.4.6):
# 1. zlib (1.2.12):    Compression library (custom configure script, not autoconf-generated)
#                      Autogenerated files tracked: 2 (configure, Makefile.in)
# 2. GMP (6.2.1):      Multiple precision arithmetic library (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 0 (regenerated via regenerate_autotools())
# 3. MPFR (3.1.6):     Multiple precision floating-point library (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 0 (regenerated via regenerate_autotools())
# 4. MPC (1.0.3):      Complex number arithmetic library (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 0 (regenerated via regenerate_autotools())
# 5. ISL (0.18):       Integer set library for polyhedral compilation (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 1 (isl_config.h.in)
# 6. Expat (2.2.6):    XML parser library for GDB (uses automake + autoconf 2.71)
#                      Autogenerated files tracked: 1 (expat_config.h.in)
#
# Note: libiconv (1.16) source is copied and autotools regenerated for build script compatibility,
# but it is only built for MinGW (Windows) targets. Docker builds use --skip_steps=mingw so libiconv is not built.
#
# The regenerate_autotools() function (build-common.sh) regenerates configure, Makefile.in,
# and other autotools files for GMP, MPFR, MPC, ISL, Expat, and libiconv before building using
# modern autoconf 2.71 (Ubuntu 24.04 default). Only binutils/gcc/gdb/newlib use legacy autoconf 2.69.
WORKDIR /root/build/gnu-tools-for-stm32
RUN echo "=== Bootstrap Stage: Building prerequisite libraries ===" && \
    echo "Layer size before build:" && du -sh /root/build/gnu-tools-for-stm32 && \
    ./build-prerequisites.sh --skip_steps=mingw && \
    echo "=== Housekeeping: Cleaning up build artifacts ===" && \
    # Clean up temporary build directories to free up space.
    # Note: Installed libraries in build-native/host-libs/usr/lib/ are preserved for the toolchain build.
    rm -rf build-native/zlib build-native/gmp build-native/mpfr \
           build-native/mpc build-native/isl build-native/expat && \
    echo "Layer size after build and cleanup:" && du -sh /root/build/gnu-tools-for-stm32 && \
    echo "Installed libraries size:" && du -sh build-native/host-libs

##########################################
### Stage 1: Binutils + GCC First     ###
###                                    ###
### Builds GNU Binutils (assembler,   ###
### linker, etc.) and GCC first pass  ###
### (C compiler only, no headers).    ###
### Required to build the C library.  ###
###                                    ###
### Script: build-binutils-gcc-first.sh
###                                    ###
### Components built:                 ###
### 1. GNU Binutils                   ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      8 (subdirectory Makefile.in) ###
###    - Tools: as, ld, ar, nm, etc.  ###
###                                    ###
### 2. GCC First Pass                 ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      15 (hand-crafted Makefile.in)###
###    - Reduced from 22 (2025-11-11) ###
###    - C compiler only, no libs     ###
##########################################
FROM bootstrap AS binutils-gcc-first

# Copy only files needed for binutils-gcc-first stage
# This improves Docker layer caching - changes to later-stage sources (newlib, gdb)
# won't invalidate the binutils-gcc-first layer cache

# Copy build script required for binutils-gcc-first
COPY build-binutils-gcc-first.sh /root/build/gnu-tools-for-stm32/

# Copy only binutils and gcc sources (prerequisites already built in bootstrap stage)
# Excluding later-stage sources (newlib, gdb) - they're not needed until later stages
COPY src/binutils /root/build/gnu-tools-for-stm32/src/binutils
COPY src/gcc /root/build/gnu-tools-for-stm32/src/gcc

# Build binutils and gcc first pass
# Script: build-binutils-gcc-first.sh
#
# Components built:
# 1. Binutils (2.35.2): GNU assembler, linker, and binary utilities (uses autoconf 2.69)
#                       Autogenerated files tracked: 8 (subdirectory Makefile.in)
#                       Tools: as, ld, ar, nm, objcopy, objdump, ranlib, readelf, size, strings, strip
# 2. GCC First Pass:    C compiler only, no standard library headers (uses autoconf 2.69)
#                       Autogenerated files tracked: 15 (hand-crafted Makefile.in)
#                       Required to build newlib in the next stage
#
# The regenerate_autotools() function (build-common.sh) uses autoconf 2.69 for binutils and gcc
# (exact version required for reproducible builds).
WORKDIR /root/build/gnu-tools-for-stm32
RUN echo "=== Binutils-GCC-First Stage: Building binutils and gcc first pass ===" && \
    echo "Layer size before build:" && du -sh /root/build/gnu-tools-for-stm32 && \
    chmod +x build-binutils-gcc-first.sh && \
    ./build-binutils-gcc-first.sh && \
    echo "=== Housekeeping: Cleaning up build artifacts ===" && \
    # Build artifacts already cleaned by build-binutils-gcc-first.sh:
    # - build-native/binutils (removed after building)
    # - build-native/gcc-first (removed after building)
    # - *.o object files (removed via find)
    # - *.la libtool files (removed via find)
    # Clean up additional unnecessary files to reduce layer size:
    # - Build logs and temporary files
    rm -rf build-native/*.log build-native/*.txt 2>/dev/null || true && \
    # - Remove any remaining .deps directories from build artifacts
    find build-native -type d -name ".deps" -exec rm -rf {} + 2>/dev/null || true && \
    # - Clean up any backup files that may have been created
    find . -name "*~" -delete 2>/dev/null || true && \
    find . -name "*.orig" -delete 2>/dev/null || true && \
    find . -name "*.rej" -delete 2>/dev/null || true && \
    echo "Layer size after build and cleanup:" && du -sh /root/build/gnu-tools-for-stm32 && \
    echo "Installed binaries size:" && du -sh install-native/bin 2>/dev/null || echo "No binaries installed yet"

##########################################
### Stage 2: Newlib                   ###
###                                    ###
### Builds newlib, the C standard     ###
### library for embedded systems.     ###
### Provides libc, libm, and runtime  ###
### libraries. Uses the GCC first     ###
### pass compiler from Stage 1.       ###
###                                    ###
### Script: build-newlib.sh           ###
###                                    ###
### Component built:                  ###
### 1. Newlib                         ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      15 (hand-crafted Makefile.in ###
###      in libgloss subdirectories)  ###
###    - Reduced from 17 (2025-11-12) ###
###    - Libraries: libc.a, libm.a,   ###
###      libg.a, crt0.o startup files ###
###    - Built with -Os for size      ###
###      optimization                 ###
###    - Modernized: 2025-11-12       ###
###      (see docs/modernization-     ###
###      newlib.md)                   ###
##########################################
FROM binutils-gcc-first AS newlib

# Copy remaining sources needed for subsequent build stages
# TODO: Future optimization - copy incrementally per stage
COPY . /root/build/gnu-tools-for-stm32/

WORKDIR /root/build/gnu-tools-for-stm32
RUN chmod +x build-newlib.sh && \
    ./build-newlib.sh

##########################################
### Stage 3: GCC Final + GDB          ###
###                                    ###
### Builds GCC final pass with C++    ###
### support (creates libstdc++) and   ###
### GDB debugger. This is the         ###
### complete compiler toolchain.      ###
###                                    ###
### Script: build-gcc-final-gdb.sh    ###
###                                    ###
### Components built:                 ###
### 1. GCC Final Pass                 ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      15 (hand-crafted Makefile.in)###
###    - Reduced from 22 (2025-11-11) ###
###    - C and C++ compiler           ###
###    - Libraries: libstdc++.a,      ###
###      libsupc++.a                  ###
###                                    ###
### 2. GDB (GNU Debugger)             ###
###    - Uses autogen (Makefile.def)  ###
###    - Uses autoconf 2.69           ###
###    - Autogenerated files tracked: ###
###      95 (most of any component,   ###
###      includes many subdirectories ###
###      like bfd, binutils, gas,     ###
###      gdb, opcodes, readline, sim) ###
###    - Debugger for ARM targets     ###
##########################################
FROM newlib AS gcc-final-gdb

WORKDIR /root/build/gnu-tools-for-stm32
RUN chmod +x build-gcc-final-gdb.sh && \
    ./build-gcc-final-gdb.sh

##########################################
### Stage 4: Runtime Libraries        ###
###                                    ###
### Finalizes runtime library         ###
### installation (libstdc++, newlib)  ###
### and removes build artifacts.      ###
###                                    ###
### Script: build-runtime-libs-       ###
###         finalize.sh                ###
###                                    ###
### Operations:                        ###
### - Verifies runtime libraries      ###
### - Links toolchain binaries to     ###
###   /usr/local/bin/                 ###
### - Cleans up build artifacts       ###
###                                    ###
### No new libraries built, no        ###
### autotools usage in this stage.    ###
##########################################
FROM gcc-final-gdb AS runtime-libs

WORKDIR /root/build/gnu-tools-for-stm32
RUN chmod +x build-runtime-libs-finalize.sh && \
    ./build-runtime-libs-finalize.sh

##########################################
### Main: Final Stage                 ###
###                                    ###
### Complete toolchain ready for use  ###
### with all runtime libraries.       ###
###                                    ###
### Inherits all built tools from     ###
### previous stages. No additional    ###
### build operations or autotools     ###
### usage in this stage.              ###
##########################################
FROM runtime-libs AS main

# Final stage - toolchain is ready for use with runtime libraries
WORKDIR /root/build/gnu-tools-for-stm32
