# generated by configure / remove this line to disable regeneration
prefix="/home/runner/work/gnu-tools-for-stm32/gnu-tools-for-stm32/build-native/host-libs/usr"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/runner/work/gnu-tools-for-stm32/gnu-tools-for-stm32/build-native/isl/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="//home/runner/work/gnu-tools-for-stm32/gnu-tools-for-stm32/src/isl/include"
package="isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "isl"
;; --help) pkg-config --help ; echo Buildscript Of "isl Library"
;; --modversion|--version) echo "0.15"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "-L/home/runner/work/gnu-tools-for-stm32/gnu-tools-for-stm32/build-native/host-libs/usr/lib" "-lisl -lgmp"
       :
;; --cflags) echo -I${includedir} "-I/home/runner/work/gnu-tools-for-stm32/gnu-tools-for-stm32/build-native/host-libs/usr/include"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
