---
name: create container - dry run

on:
  workflow_dispatch:
#  merge_group:

#  pull_request_target:
#    branches: ['dependabot/**']

  pull_request:
    # Run on pull requests (default types: opened, synchronize, reopened)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  dry-run-docker-build:
    name: Build Container (Dry Run)
    uses: ./.github/workflows/build-container.yml
    with:
      push: false
      tags: gnu-tools-for-stm32:latest
    permissions:
      contents: read
      packages: write
