---
name: Build toolchain

on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool \
                                   m4 gettext autopoint pkg-config \
                                   build-essential bison flex texinfo

      - name: Build Prerequisites
        shell: bash
        run: |
          ./build-prerequisites.sh
